name: Update vpinmdb json file 

on:
  push:

  workflow_dispatch:

jobs:
  update-vpinmdb:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        run: |
          git clone --no-checkout --depth 1 https://github.com/superhac/vpinmediadb.git
          git ls-tree --full-name --name-only -r HEAD


